### ISSUE TITLE
User forget password feature

### ISSUE THREAD

**Issue by meassamrong** [tfd-ed/sarpheab-api#14]
## User forget password feature
im interested in making a new feature to handle users forgetting passwords

## To- Do
- allow the user to send requests and forget their password with their email
- Use   [sending blue](https://my.brevo.com/)  SMTP to send an email to the user with a magic url+token
- Generate specific token parame and save it as temporary to DB for comparison when user's requests with Token + URL that we send to email
- the URL request forget password will expire in one time request and 1 hour.
- Maybe need to modify user DB model to add a new object isRequesResetPassword: { isReset : true, token_url: String, req_date: new Date() }
- And I would like to request .env temple as well 😅.

**Comment by tfd-ed** [comment]
@meassamrong , nice proposal, please proceed
