### ISSUE TITLE
Implement Swagger (Internal API Test)

### ISSUE THREAD

**Issue by KimangKhenng** [tfd-ed/sarpheab-api#2]
### Current Issue
This project lack internal API testing tool making it hard for advanced API call with complexy query.
### To-do
- Add Swagger module
- Create a new route to display Swagger-UI (api/docs)
### Resources
- [Express Swagger UI](https://www.npmjs.com/package/swagger-ui-express)

@tfd-ed Please help review my proposal

**Comment by tfd-ed** [comment]
@KimangKhenng , Thanks for your proposal. I think having internal API test is good in the long run.
You may create a new directory that may require DTO for some Swagger route.
